### PR TITLE
Fix determine_output_filename function in api.py to handle appended numbers in file names

### PR DESCRIPTION
**Pull request by rmcc3**
The determine_output_filename function in the api.py file was not returning the correct file name when files had an appended number. This caused issues in the Gradio UI where the audio preview was not updating to newly generated files with appended numbers in their names.

This commit fixes the issue by updating the determine_output_filename function to correctly handle appended numbers in file names. Now, the function properly returns the correct file name, and the UI audio preview updates as expected.

Fixes issue #43

### CODE REVIEW

**Comment by rmcc3** [comment]
A little note: Should consider a ".editorconfig" that forces formatting to prevent the 100+ line "changes" as shown in the commit preview.

**Comment by rmcc3** [comment]
Update: This change seems to have introduced a UI-breaking bug that seems to hit randomly. Will reopen once I find the cause.

**Comment by rmcc3** [comment]
So, it seems the issue is coming from "Silence Between Segment". Unrelated to this change. Just happened to appear. The issue is still present without the change.

**Comment by JonathanFly** [comment]
Thanks, I'll look at this tonight. Yeah the filename stuff is a mess all over. Rip it all out and simply, some day.

**Comment by JonathanFly** [comment]
Added an issue for the .editorconfig, so I don't forget.

**Pull request closed without merging**
